### ISSUE TITLE
This netbeans patch 2 to netbeans 8.2

### ISSUE THREAD

**Issue by filippiR** [junichi11/cakephp-netbeans#136]
the plugin stopped working after the last update of netbeans, I know that the new version is working however there are systems that have been developed in previous versions and is ruin to support without the plugin.

**Comment by junichi11** [comment]
What do you expect?

**Comment by filippiR** [comment]
I would like a new release with support for netbeans 8.2 patch 2

**Comment by junichi11** [comment]
New version already released: 
https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.15.1

Did you try it?

**Comment by filippiR** [comment]
I had not tried. I had tried just update through netbeans -> Plug-ins.
I'm sorry I bothered you with this, and thanks for the help.

**Comment by junichi11** [comment]
No problem :)

Usually, I upload a new nbm to GitHub releases[1] and Plugin Portal[2] when I create it. 
But you cannot directly update it from NetBeans IDE soon because it needs verifications by two verifiers. So, please try to check the web sites once such this case.

BTW, you can update it from NetBeans IDE now ;)

[1] https://github.com/junichi11/cakephp-netbeans/releases
[2] http://plugins.netbeans.org/plugin/44579/php-cakephp-framework

Thanks.

**Comment by atlet** [comment]
Great, it's working now. Tnx!
